export type DebuggerPageOptions = {
  appUrl?: string
  title?: string
}

export function renderDebuggerPage(options: DebuggerPageOptions = {}) {
  const appUrl = options.appUrl ?? '/'
  const title = options.title ?? 'Shopify Debugger'
  const escapedAppUrl = escapeHtml(appUrl)
  const escapedTitle = escapeHtml(title)

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapedTitle}</title>
  <style>
    :root {
      color-scheme: light;
      --bg: #f6f6f7;
      --panel: #ffffff;
      --border: #d1d5db;
      --text: #1f2937;
      --muted: #6b7280;
      --primary: #303030;
      --shadow: 0 24px 80px rgba(15, 23, 42, 0.16);
    }

    * { box-sizing: border-box; }

    body {
      margin: 0;
      min-height: 100vh;
      background: var(--bg);
      color: var(--text);
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }

    header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 16px;
      height: 58px;
      padding: 0 18px;
      border-bottom: 1px solid var(--border);
      background: var(--panel);
    }

    header strong { display: block; font-size: 14px; }
    header small { display: block; color: var(--muted); margin-top: 2px; }

    .actions { display: flex; align-items: center; gap: 8px; }

    button, input {
      border: 1px solid var(--border);
      border-radius: 8px;
      background: #fff;
      color: var(--text);
      font: inherit;
      padding: 8px 10px;
    }

    button { cursor: pointer; }
    button.primary { background: var(--primary); color: #fff; border-color: var(--primary); }
    input { width: min(520px, 46vw); }

    main {
      display: grid;
      grid-template-columns: 1fr 360px;
      gap: 14px;
      height: calc(100vh - 58px);
      padding: 14px;
    }

    .frame-card, aside {
      overflow: hidden;
      border: 1px solid var(--border);
      border-radius: 16px;
      background: var(--panel);
      box-shadow: var(--shadow);
    }

    .frame-card { position: relative; }

    iframe {
      width: 100%;
      height: 100%;
      border: 0;
      background: #fff;
    }

    aside {
      display: flex;
      flex-direction: column;
      min-width: 0;
    }

    .aside-header {
      border-bottom: 1px solid var(--border);
      padding: 14px;
    }

    .aside-header h2 {
      margin: 0;
      font-size: 14px;
    }

    .aside-header p {
      margin: 6px 0 0;
      color: var(--muted);
      font-size: 12px;
      line-height: 1.45;
    }

    .log {
      flex: 1;
      overflow: auto;
      padding: 12px;
    }

    .event {
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 10px;
      background: #fff;
    }

    .event + .event { margin-top: 8px; }

    .event-meta {
      display: flex;
      justify-content: space-between;
      gap: 10px;
      font-size: 12px;
    }

    .event-meta span { color: var(--muted); }

    pre {
      overflow: auto;
      max-height: 180px;
      margin: 8px 0 0;
      border-radius: 8px;
      background: #111827;
      color: #d1fae5;
      padding: 8px;
      font-size: 11px;
      line-height: 1.45;
    }

    .empty {
      color: var(--muted);
      font-size: 13px;
      line-height: 1.5;
    }

    @media (max-width: 980px) {
      main { grid-template-columns: 1fr; }
      aside { display: none; }
      input { width: 44vw; }
    }
  </style>
</head>
<body>
  <header>
    <div>
      <strong>${escapedTitle}</strong>
      <small>Local shell route generated by @yan-ad/shopify-debugger</small>
    </div>
    <form class="actions" id="debugger-form">
      <input id="debugger-url" value="${escapedAppUrl}" aria-label="App URL" />
      <button type="submit" class="primary">Load</button>
      <button type="button" id="debugger-refresh">Refresh</button>
    </form>
  </header>
  <main>
    <section class="frame-card">
      <iframe id="debugger-frame" src="${escapedAppUrl}" title="Debugged Shopify app"></iframe>
    </section>
    <aside>
      <div class="aside-header">
        <h2>Shell events</h2>
        <p>
          Use this page as a lightweight iframe host. The app inside still uses
          <code>useAppBridge()</code>; the Vite plugin aliases it to the local shim when debugger mode is enabled.
        </p>
      </div>
      <div class="log" id="debugger-log">
        <p class="empty">No iframe messages yet.</p>
      </div>
    </aside>
  </main>
  <script type="module">
    const frame = document.getElementById('debugger-frame')
    const input = document.getElementById('debugger-url')
    const form = document.getElementById('debugger-form')
    const refresh = document.getElementById('debugger-refresh')
    const log = document.getElementById('debugger-log')
    const events = []

    function render() {
      if (events.length === 0) {
        log.innerHTML = '<p class="empty">No iframe messages yet.</p>'
        return
      }

      log.innerHTML = events.map((event) => {
        const payload = event.payload === undefined ? '' : '<pre>' + escapeHtml(JSON.stringify(event.payload, null, 2)) + '</pre>'
        return '<article class="event"><div class="event-meta"><strong>' + escapeHtml(event.type) + '</strong><span>' + escapeHtml(event.time) + '</span></div>' + payload + '</article>'
      }).join('')
    }

    function push(type, payload) {
      events.unshift({ type, payload, time: new Date().toLocaleTimeString() })
      events.splice(50)
      render()
    }

    function escapeHtml(value) {
      return String(value).replace(/[&<>'"]/g, (char) => ({
        '&': '&amp;',
        '<': '&lt;',
        '>': '&gt;',
        "'": '&#39;',
        '"': '&quot;',
      }[char]))
    }

    form.addEventListener('submit', (event) => {
      event.preventDefault()
      frame.src = input.value || '/'
      push('frame.load', { url: frame.src })
    })

    refresh.addEventListener('click', () => {
      frame.contentWindow?.location.reload()
      push('frame.refresh')
    })

    window.addEventListener('message', (event) => {
      push('window.message', event.data)
    })
  </script>
</body>
</html>`
}

function escapeHtml(value: string) {
  return value.replace(/[&<>'"]/g, (char) => {
    switch (char) {
      case '&': return '&amp;'
      case '<': return '&lt;'
      case '>': return '&gt;'
      case "'": return '&#39;'
      case '"': return '&quot;'
      default: return char
    }
  })
}
