export type DebuggerPageOptions = {
  appUrl?: string;
  title?: string;
};

export function renderDebuggerPage(options: DebuggerPageOptions = {}) {
  const appUrl = options.appUrl ?? "/";
  const title = options.title ?? "Shopify Debugger";
  const escapedAppUrl = escapeHtml(appUrl);
  const escapedTitle = escapeHtml(title);

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapedTitle}</title>
  <script type="module" src="https://cdn.shopify.com/shopifycloud/polaris.js"></script>
  <style>
    :root {
      color-scheme: light;
      --bg: radial-gradient(1200px 600px at -10% -10%, #f8fafc 0%, #f3f4f6 48%, #eceff3 100%);
      --panel: #ffffff;
      --border: #d8dde3;
      --text: #111827;
      --muted: #6b7280;
      --primary: #1f2937;
      --subtle: #f7f8fa;
      --surface: #f1f5f9;
      --shadow: 0 18px 56px rgba(15, 23, 42, 0.14);
    }

    * { box-sizing: border-box; }

    body {
      margin: 0;
      min-height: 100vh;
      background: var(--bg);
      color: var(--text);
      font-family: Manrope, "Avenir Next", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }

    header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 16px;
      min-height: 68px;
      padding: 10px 18px;
      border-bottom: 1px solid var(--border);
      background: rgba(255, 255, 255, 0.86);
      backdrop-filter: blur(8px);
    }

    header strong { display: block; font-size: 14px; }
    header small { display: block; color: var(--muted); margin-top: 2px; }

    .actions { display: flex; align-items: center; gap: 8px; }

    button, input, select, textarea {
      border: 1px solid var(--border);
      border-radius: 10px;
      background: #fff;
      color: var(--text);
      font: inherit;
      padding: 9px 11px;
    }

    button { cursor: pointer; }
    button.primary { background: var(--primary); color: #fff; border-color: var(--primary); }
    button:hover { border-color: #b8c0cc; }
    input { width: min(520px, 46vw); }
    select, textarea { width: 100%; }
    textarea { min-height: 128px; resize: vertical; font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 12px; }

    main {
      display: grid;
      grid-template-columns: 1fr 390px;
      gap: 16px;
      height: calc(100vh - 58px);
      padding: 16px;
    }

    .frame-card, aside {
      overflow: hidden;
      border: 1px solid var(--border);
      border-radius: 14px;
      background: var(--panel);
      box-shadow: var(--shadow);
    }

    .frame-card { position: relative; }

    iframe {
      width: 100%;
      height: 100%;
      border: 0;
      background: #fff;
    }

    aside {
      display: flex;
      flex-direction: column;
      min-width: 0;
    }

    .aside-header, .controls {
      border-bottom: 1px solid var(--border);
      padding: 14px;
    }

    .aside-header h2 {
      margin: 0;
      font-size: 14px;
    }

    .aside-header p, .hint {
      margin: 6px 0 0;
      color: var(--muted);
      font-size: 12px;
      line-height: 1.45;
    }

    .controls {
      display: grid;
      gap: 12px;
      background: var(--subtle);
    }

    .control-row { display: grid; gap: 6px; }
    .control-row label { font-weight: 650; font-size: 12px; }
    .button-row { display: flex; flex-wrap: wrap; gap: 8px; }

    .status-pill {
      display: inline-flex;
      width: fit-content;
      align-items: center;
      border-radius: 999px;
      background: var(--surface);
      color: var(--muted);
      padding: 4px 8px;
      font-size: 12px;
      font-weight: 650;
    }

    .status-pill[data-ready="true"] { background: #dcfce7; color: #166534; }
    .status-pill[data-pending="true"] { background: #fef3c7; color: #92400e; }

    .log {
      flex: 1;
      overflow: auto;
      padding: 12px;
    }

    .event {
      border: 1px solid var(--border);
      border-radius: 10px;
      padding: 10px;
      background: var(--subtle);
    }

    .event + .event { margin-top: 8px; }

    .event-meta {
      display: flex;
      justify-content: space-between;
      gap: 10px;
      font-size: 12px;
    }

    .event-meta span { color: var(--muted); }

    pre {
      overflow: auto;
      max-height: 180px;
      margin: 8px 0 0;
      border-radius: 8px;
      background: #111827;
      color: #e5e7eb;
      padding: 8px;
      font-size: 11px;
      line-height: 1.45;
    }

    .empty {
      color: var(--muted);
      font-size: 13px;
      line-height: 1.5;
    }

    @media (max-width: 980px) {
      main { grid-template-columns: 1fr; }
      aside { display: none; }
      input { width: 44vw; }
    }
  </style>
</head>
<body>
  <header>
    <div>
      <strong>${escapedTitle}</strong>
      <small>Zero-client-code local shell route generated by shopify-debugger</small>
    </div>
    <form class="actions" id="debugger-form">
      <input id="debugger-url" value="${escapedAppUrl}" aria-label="App URL" />
      <button type="submit" class="primary">Load</button>
      <button type="button" id="debugger-refresh">Refresh</button>
    </form>
  </header>
  <main>
    <section class="frame-card">
      <iframe id="debugger-frame" src="${escapedAppUrl}" title="Debugged Shopify app"></iframe>
    </section>
    <aside>
      <div class="aside-header">
        <h2>App Bridge Debugger</h2>
        <p>
          The app inside still imports <code>useAppBridge()</code> normally. The Vite plugin aliases it to the local shim and streams events to this shell.
        </p>
      </div>
      <div class="controls">
        <span class="status-pill" id="debugger-ready" data-ready="false">waiting for iframe</span>
        <span class="status-pill" id="debugger-pending" data-pending="false">no pending picker</span>
        <div class="control-row">
          <label for="resource-mode">Resource picker mode</label>
          <select id="resource-mode">
            <option value="success">success</option>
            <option value="cancel">cancel</option>
            <option value="error">error</option>
            <option value="manual">manual</option>
          </select>
        </div>
        <div class="control-row">
          <label for="resource-response">Resource picker success response JSON</label>
          <textarea id="resource-response">${escapeHtml(JSON.stringify(defaultResourceResponse, null, 2))}</textarea>
        </div>
        <div class="button-row">
          <button type="button" id="resource-save">Save response</button>
          <button type="button" id="resource-resolve" class="primary">Resolve pending</button>
          <button type="button" id="resource-cancel">Cancel pending</button>
          <button type="button" id="resource-error">Error pending</button>
          <button type="button" id="events-clear">Clear events</button>
        </div>
      </div>
      <div class="log" id="debugger-log">
        <p class="empty">No App Bridge calls yet.</p>
      </div>
    </aside>
  </main>
    <s-modal id="shell-modal" size="base">
      <s-text id="shell-modal-text">No active modal.</s-text>
      <s-button slot="secondary-actions" id="shell-modal-close" variant="secondary">
        Close modal
      </s-button>
    </s-modal>
  <script type="module">
    const frame = document.getElementById('debugger-frame')
    const input = document.getElementById('debugger-url')
    const form = document.getElementById('debugger-form')
    const refresh = document.getElementById('debugger-refresh')
    const log = document.getElementById('debugger-log')
    const ready = document.getElementById('debugger-ready')
    const pending = document.getElementById('debugger-pending')
    const mode = document.getElementById('resource-mode')
    const response = document.getElementById('resource-response')
    const saveResponse = document.getElementById('resource-save')
    const resolvePicker = document.getElementById('resource-resolve')
    const cancelPicker = document.getElementById('resource-cancel')
    const errorPicker = document.getElementById('resource-error')
    const clearEvents = document.getElementById('events-clear')
    const shellModal = document.getElementById('shell-modal')
    const shellModalText = document.getElementById('shell-modal-text')
    const shellModalClose = document.getElementById('shell-modal-close')
    const events = []
    let latestState
    let currentShellModalId = ''
    let currentShellModalHeading = ''
    let suppressShellModalHideEvent = false

    function renderShellModal(state) {
      const activeModals = Array.isArray(state?.activeModals) ? state.activeModals : []
      // Support modal metadata: [{id, heading}] or [id]
      let currentModalId = ''
      let heading = ''
      if (activeModals.length > 0) {
        const modal = activeModals[0]
        if (typeof modal === 'object' && modal !== null) {
          currentModalId = modal.id || ''
          heading = modal.heading || ''
        } else {
          currentModalId = modal
        }
      }
      const isOpen = Boolean(currentModalId)

      currentShellModalId = currentModalId
      currentShellModalHeading = heading
      shellModalClose.disabled = !isOpen

      if (!isOpen) {
        shellModalText.textContent = 'No active modal.'
        shellModal.removeAttribute('heading')
        if (typeof shellModal.hideOverlay === 'function') {
          suppressShellModalHideEvent = true
          shellModal.hideOverlay()
          queueMicrotask(() => {
            suppressShellModalHideEvent = false
          })
        }
        return
      }

      // Prefer heading from app, fallback to modal id
      const displayHeading = heading || currentModalId
      shellModal.setAttribute('heading', displayHeading)
      shellModalText.textContent = displayHeading
        ? 'App Bridge modal: ' + displayHeading
        : 'App Bridge modal is open in debugger shell.'
      if (typeof shellModal.showOverlay === 'function') {
        shellModal.showOverlay()
      }
    }

    function send(command, payload) {
      frame.contentWindow?.postMessage({ source: 'shopify-debugger-shell', command, payload }, '*')
    }

    function renderEvents() {
      if (events.length === 0) {
        log.innerHTML = '<p class="empty">No App Bridge calls yet.</p>'
        return
      }

      log.innerHTML = events.map((event) => {
        const payload = event.payload === undefined ? '' : '<pre>' + escapeHtml(JSON.stringify(event.payload, null, 2)) + '</pre>'
        return '<article class="event"><div class="event-meta"><strong>' + escapeHtml(event.type) + '</strong><span>' + escapeHtml(event.time) + '</span></div>' + payload + '</article>'
      }).join('')
    }

    function renderState(state) {
      latestState = state
      if (!state) return

      mode.value = state.resourcePickerMode || 'success'
      ready.textContent = 'iframe connected'
      ready.dataset.ready = 'true'

      const hasPending = Boolean(state.pendingResourcePicker)
      pending.textContent = hasPending ? 'resource picker pending' : 'no pending picker'
      pending.dataset.pending = String(hasPending)
      renderShellModal(state)
    }

    function push(type, payload) {
      events.unshift({ type, payload, time: new Date().toLocaleTimeString() })
      events.splice(100)
      renderEvents()
    }

    function escapeHtml(value) {
      return String(value).replace(/[&<>'"]/g, (char) => ({
        '&': '&amp;',
        '<': '&lt;',
        '>': '&gt;',
        "'": '&#39;',
        '"': '&quot;',
      }[char]))
    }

    function parseResponse() {
      try {
        return JSON.parse(response.value)
      } catch (error) {
        alert('Invalid JSON: ' + error.message)
        throw error
      }
    }

    form.addEventListener('submit', (event) => {
      event.preventDefault()
      frame.src = input.value || '/'
      ready.textContent = 'waiting for iframe'
      ready.dataset.ready = 'false'
      push('frame.load', { url: frame.src })
    })

    refresh.addEventListener('click', () => {
      frame.contentWindow?.location.reload()
      ready.textContent = 'waiting for iframe'
      ready.dataset.ready = 'false'
      push('frame.refresh')
    })

    frame.addEventListener('load', () => {
      send('getState')
    })

    mode.addEventListener('change', () => {
      send('setResourcePickerMode', mode.value)
    })

    saveResponse.addEventListener('click', () => {
      send('setResourcePickerResponse', parseResponse())
    })

    resolvePicker.addEventListener('click', () => {
      send('resolveResourcePicker', parseResponse())
    })

    cancelPicker.addEventListener('click', () => {
      send('resolveResourcePicker')
    })

    errorPicker.addEventListener('click', () => {
      send('rejectResourcePicker')
    })

    clearEvents.addEventListener('click', () => {
      events.length = 0
      renderEvents()
      send('clearEvents')
    })

    shellModalClose.addEventListener('click', () => {
      if (!currentShellModalId) return
      send('hideModal', currentShellModalId)
    })

    shellModal.addEventListener('hide', () => {
      if (suppressShellModalHideEvent) return
      if (!currentShellModalId) return
      send('hideModal', currentShellModalId)
    })

    window.addEventListener('message', (event) => {
      const message = event.data
      if (message?.source !== 'shopify-debugger-client') return

      if (message.type === 'ready') {
        renderState(message.payload)
        push('client.ready', message.payload)
        return
      }

      if (message.type === 'state') {
        renderState(message.payload)
        return
      }

      if (message.type === 'event') {
        renderState(message.payload?.state)
        push(message.payload?.event?.type || 'appBridge.event', message.payload?.event?.payload)
      }
    })
  </script>
</body>
</html>`;
}

const defaultResourceResponse = [
  {
    id: "gid://shopify/Product/1",
    title: "Debug Product",
    handle: "debug-product",
    variants: [
      {
        id: "gid://shopify/ProductVariant/1",
        title: "Default Title",
        price: "10.00",
        sku: "DEBUG-1",
      },
    ],
  },
];

function escapeHtml(value: string) {
  return value.replace(/[&<>'"]/g, (char) => {
    switch (char) {
      case "&":
        return "&amp;";
      case "<":
        return "&lt;";
      case ">":
        return "&gt;";
      case "'":
        return "&#39;";
      case '"':
        return "&quot;";
      default:
        return char;
    }
  });
}
